name: Deploy React App to Apache Server

on:
  push:
    branches:
      - main  # Change this to your target branch if needed

jobs:
  deploy:
    name: 🚀 Deploy to Apache Server
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: Install nvm and Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          source ~/.bashrc
          nvm install 16  # Install a specific version of Node.js (adjust as necessary)
          nvm use 16

      - name: Clean pm2 installation
        run: |
          sudo npm uninstall -g pm2
          sudo rm -rf /usr/lib/node_modules/pm2
          sudo rm -rf ~/.pm2
          sudo npm cache clean --force

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Clean previous installations
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: 📦 Install Dependencies & Build React App
        run: |
          export CI=false  # Prevent ESLint warnings from failing the build
          npm install --force  # Force installation to avoid conflicts
          npm run build

      - name: 🚚 Ensure Directories Exist on Remote Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "Connecting to $SERVER_HOST to ensure necessary directories exist..."
          sshpass -p "$SERVER_PASSWORD" ssh -tt -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST << 'EOF'
            echo "✅ Creating directories if they do not exist..."
            sudo mkdir -p /var/www/my-web-app/node_modules
            sudo mkdir -p /var/www/my-web-app
            sudo chown -R www-data:www-data /var/www/my-web-app
            exit
          EOF

      - name: 🚚 Transfer Files to Apache Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "Connecting to $SERVER_HOST..."
          sshpass -p "$SERVER_PASSWORD" ssh -tt -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST << 'EOF'
            echo "✅ Connected to server. Cleaning old files..."
            sudo rm -rf /var/www/my-web-app/*  # Remove old build files
            sudo chown -R www-data:www-data /var/www/my-web-app/
            exit
          EOF

          # Upload new build files
          echo "📤 Uploading new build files..."
          sshpass -p "$SERVER_PASSWORD" scp -r build/* $SERVER_USERNAME@$SERVER_HOST:/var/www/my-web-app/

          # Ensure file ownership after upload
          sshpass -p "$SERVER_PASSWORD" ssh -tt -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST << 'EOF'
            echo "Ensuring correct file permissions..."
            sudo chown -R www-data:www-data /var/www/my-web-app/
            exit
          EOF

      # Optional: Restart Apache server (if necessary)
      # - name: 🔁 Restart Apache Server
      #   if: always()
      #   env:
      #     SERVER_HOST: ${{ secrets.SERVER_HOST }}
      #     SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      #     SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      #   run: |
      #     sshpass -p "$SERVER_PASSWORD" ssh -tt -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST << 'EOF'
      #       echo "🔁 Restarting Apache..."
      #       sudo systemctl restart apache2
      #       exit
      #     EOF
