name: Test Deploy Connection

on:
  push:
    branches:
      - main

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Repository
        uses: actions/checkout@v4

      - name: ✅ Install SSH & SSHPass
        run: sudo apt-get install -y sshpass

      - name: 🧪 Test SSH to Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "🚀 Testing SSH connection to $SERVER_HOST..."
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "echo ✅ Hello from $SERVER_HOST && uptime"
