name: Deploy Node.js Application to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Change this if using a different version

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          npm install
          npm run build # If you have a build script, otherwise skip this

      # Step 4: Transfer Application Files to Server
      - name: Transfer Application Files to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" rsync -avz --exclude 'node_modules' --exclude '.git' ./ $SERVER_USER@$SERVER_IP:/var/www/my-web-app/

      # Step 5: Restart Application on Server
      - name: Restart Application on Server
        env:
          SERVER_IP: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            # Navigate to application directory
            cd /var/www/my-web-app

            # Install dependencies (if not already installed)
            npm install --production

            # Stop existing application if running
            pm2 stop my-web-app || true
            pm2 delete my-web-app || true

            # Start the application with PM2
            pm2 start app.js --name my-web-app

            # Save PM2 process to restart on reboot
            pm2 save
          EOF
