name: Deploy Node.js Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use your Node.js version here

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        npm install
        npm run build # Optional, only if using build script

    # Step 4: Transfer Application Files to Server
    - name: Transfer Application Files to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" rsync -avz --exclude 'node_modules' --exclude '.git' ./ $SERVER_USER@$SERVER_IP:/var/www/my-web-app

    # Step 5: SSH into Server and Restart Application
    - name: Restart Application on Server
      env:
        SERVER_IP: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          # Navigate to the application directory
          cd /var/www/my-web-app
          
          # Install dependencies
          npm install --production
          
          # Stop existing application (if running)
          pm2 stop my-web-app || true
          pm2 delete my-web-app || true
          
          # Start application with PM2
          pm2 start app.js --name my-web-app
          
          # Save PM2 configuration to restart on reboot
          pm2 save
        EOF
