name: Deploy Express App with PM2 and Run ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH & SSHPass
        run: sudo apt-get install -y sshpass

      - name: Upload All Files to Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "📦 Uploading files to the server..."
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            echo "🧹 Cleaning old files..."
            sudo rm -rf /var/www/my-web-app
            mkdir -p /var/www/my-web-app
            exit
          EOF

          echo "🚀 Uploading project files..."
          sshpass -p "$SERVER_PASSWORD" scp -r ./* $SERVER_USER@$SERVER_HOST:/var/www/my-web-app/

      - name: Install and Restart App on Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "🔧 Installing dependencies and starting app..."
          sshpass -p "$SERVER_PASSWORD" ssh -tt -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << EOF
            cd /var/www/my-web-app
            npm install
            pm2 delete my-web-app || true
            pm2 start app.js --name my-web-app
            pm2 save
            exit
          EOF
