name: Deploy React App to Apache Server

on:
  push:
    branches:
      - main  # Use your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH & SSHPass
        run: sudo apt-get install -y sshpass

      - name: Debug SSH Variables
        run: |
          echo "Server Host: ${{ secrets.SERVER_HOST }}"
          echo "Server Username: ${{ secrets.SERVER_USER }}"

      - name: Install Node.js Dependencies & Build React App
        run: |
          export CI=false  # Prevent ESLint warnings from failing the build
          npm install
          npm run build

      - name: Serve React App Locally
        run: |
          npx serve -s build -l 3000 &
          sleep 15  # Give server time to fully start

      - name: Run OWASP ZAP Full Scan (Security Check)
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://localhost:3000'

      - name: Transfer Files to Apache Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -tt -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST << 'EOF'
            echo "✅ Connected to $SERVER_HOST"
            sudo rm -rf /var/www/html/*
            exit
EOF
          sshpass -p "$SERVER_PASSWORD" scp -r build/* $SERVER_USERNAME@$SERVER_HOST:/var/www/html/
