name: Deploy React App to Apache Server

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH & SSHPass
        run: sudo apt-get install -y sshpass

      - name: Debug SSH Variables
        run: |
          echo "Server Host: ${{ secrets.SERVER_HOST }}"
          echo "Server Username: ${{ secrets.SERVER_USERNAME }}"

      - name: Install Node.js Dependencies & Build React App
        run: |
          export CI=false  # Prevent ESLint warnings from failing the build
          npm install
          npm run build

      - name: Serve React App for ZAP Scan
        run: |
          # Serve the app on port 3000
          npx serve -s build -l 3000 &
          sleep 10  # Allow some time for the server to start

      - name: Run OWASP ZAP Scan (Security Check)
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: 'http://localhost:3000'  # Ensure the React app is running on this URL
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}  # Ensure you have your ZAP API key stored in secrets

      - name: Transfer Files to Apache Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -tt -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST << 'EOF'
            echo "✅ Successfully connected to $SERVER_HOST"
            
            # Clear old files and upload new ones
            sudo rm -rf /var/www/html/*
            exit
           EOF

           sshpass -p "$SERVER_PASSWORD" scp -r build/* $SERVER_USERNAME@$SERVER_HOST:/var/www/html/
