
name: Deploy Web App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-web-app .
      - name: Save Docker Image
        run: |
          docker save my-web-app -o my-web-app.tar
      - name: Transfer Docker Image to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no my-web-app.tar $SERVER_USER@$SERVER_IP:/root/
      - name: Deploy Application on Server
        env:

          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -tt -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST << 'EOF'
            echo "✅ Connected to $SERVER_HOST"
            sudo rm -rf /var/www/html/*
            exit


          SERVER_IP: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            docker stop my-web-app || true
            docker rm my-web-app || true
            docker load -i /root/my-web-app.tar
            docker run -d --name my-web-app -p 80:3000 my-web-app
            docker system prune -f
          EOF

